apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: myapp:green
        ports:
        - containerPort: 8080
