apiVersion: v1
kind: Service
metadata:
  name: myapp-green
  namespace: bluegreen
spec:
  selector:
    app: myapp
    version: green
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: LoadBalancer
  # type: ClusterIP
