apiVersion: v1
kind: Service
metadata:
  name: myapp-blue
  namespace: bluegreen
spec:
  selector:
    app: myapp
    version: blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
  # type: ClusterIP
