apiVersion: v1
kind: Service
metadata:
  name: myapp-blue
  namespace: bluegreen
spec:
  type: NodePort
  selector:
    app: myapp
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081 
  
