apiVersion: v1
kind: Service
metadata:
  name: myapp-green
  namespace: bluegreen
spec:
  type: NodePort
  selector:
    app: myapp
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30082
  
